name = "zlg"
compatibility_date = "2026-05-15"
pages_build_output_dir = "."

# KV namespace for status overrides + LGM message cache.
# After running `wrangler kv namespace create OVERRIDES`, paste the returned id here
# and the same id under [[env.preview.kv_namespaces]].
[[kv_namespaces]]
binding = "OVERRIDES"
id = "ae46a093c89a4258992cef904b0f3ff5"

[[env.preview.kv_namespaces]]
binding = "OVERRIDES"
id = "f2cbab52a9eb461d8b1deadba1dda11e"
